spring:
  application:
    name: ironvault-merchants

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8083}

app:
  auth:
    url: ${AUTH_URL}
    internal-api-key: ${INTERNAL_API_KEY}

mercadopago:
  client-id: ${MP_CLIENT_ID}
  client-secret: ${MP_CLIENT_SECRET}
  redirect-uri: ${MP_REDIRECT_URI}